language: node_js
node_js:
- 8.9.4
addons:
  ssh_known_hosts: 165.227.197.233
install: npm install
script:
- npm run gulp
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_8fede080f25c_key -iv $encrypted_8fede080f25c_iv
  -in deploy.enc -out /tmp/deploy -d
deploy:
  provider: script
  skip_cleanup: true
  script: bash ./scripts/deploy.sh